language: node_js
node_js:
  - "stable"
install:
  - npm install --build-from-source
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - librsvg2-dev
      - g++-4.9
env:
  - CXX=g++-4.9
sudo: false
before_install:
  - unset _JAVA_OPTIONS
after_success: 'npm run coveralls'